
export const HeartData = [
    {
        id: 'p1',
        imageUrl: 'https://cdn.pixabay.com/photo/2017/01/07/15/07/bible-1960635_640.jpg',
        title: '웹소설작가가 6년간 정리한 <단어 리스트>',
        creator: '펀드',
        description: '웹소설 작가가 직접 정리한 단어 리스트 & 내가 직접 쓰는 나만의 단어 리스트',
        percentage: 787,
        currentAmount: 3937000,
        remainingDays: 41,
        liked: true,
        notified: false,
        status: 'ongoing',
        startDate: '2025-05-01',
    },
    {
        id: 'p2',
        imageUrl: 'https://cdn.pixabay.com/photo/2016/10/26/10/05/book-1771073_640.jpg',
        title: '단어&문장 묘사집 1000',
        creator: '플로우',
        description: '작품 창작에 도움이 될 묘사집',
        percentage: 14,
        currentAmount: 148000,
        remainingDays: 27,
        liked: true,
        notified: false,
        status: 'ongoing',
        startDate: '2025-05-15',
    },
    {
        id: 'p3',
        imageUrl: 'https://cdn.pixabay.com/photo/2025/05/28/00/07/network-9626186_640.jpg',
        title: 'SF 현대물리 상태창 대사집 UI +100',
        creator: 'Fund',
        description: 'SF스타일 대사집 UI 브러시 100종 세트입니다. 스케치업 웹툰 배경구성도 있어요!',
        percentage: 38,
        currentAmount: 191000,
        remainingDays: 27,
        liked: true,
        notified: false,
        status: 'ongoing',
        startDate: '2025-05-10',
    },
    {
        id: 'p4',
        imageUrl: 'https://cdn.pixabay.com/photo/2021/10/06/20/22/uhd-6686651_640.jpg',
        title: '3D 텍스쳐 100종 + AI 제작 가이드북',
        creator: 'Flow',
        description: '실무에 바로 쓰는 3D 텍스쳐 100+ 무료 AI 제작 가이드팩',
        percentage: 12,
        currentAmount: 180000,
        remainingDays: 27,
        liked: true,
        notified: false,
        status: 'ongoing',
        startDate: '2025-05-05',
    },
    {
        id: 'p5',
        imageUrl: 'https://cdn.pixabay.com/photo/2016/11/29/07/21/book-1868068_640.jpg',
        title: '새로운 모험의 시작: 판타지 월드 가이드',
        creator: 'KDT',
        description: '당신만의 세계관을 만들 수 있는 판타지 월드 가이드북',
        percentage: 0,
        currentAmount: 0,
        remainingDays: 10,
        liked: false,
        notified: false,
        status: 'upcoming',
        startDate: '2025-06-20',
    },
    {
        id: 'p6',
        imageUrl: 'https://cdn.pixabay.com/photo/2018/01/17/18/43/book-3088775_640.jpg',
        title: '우주선을 타고 떠나는 일러스트집',
        creator: '프로젝트',
        description: '몽환적인 우주 일러스트와 숨겨진 이야기들',
        percentage: 0,
        currentAmount: 0,
        remainingDays: 15,
        liked: false,
        notified: false,
        status: 'upcoming',
        startDate: '2025-06-25',
    },
];